### ISSUE TITLE
Support IDE ?

### ISSUE THREAD

**Issue by xolod79** [harbaum/MiSTeryNano#11]
Till, thank you for your great work on MiST and now Tang.
I would like to ask, are you planning to support the ide.v interface?
I'm writing the Core of a rare computer that uses an IDE and would like to transfer it to Tang.

**Comment by harbaum** [comment]
The Atari ST mainly used ACSI, a simplified SCSI subset and I will implement that. So I have no real need for IDE.

What machine is it you are implementing? IDE isn't that old. But it's imho not that complex either and should be quite straightforward to implement.

**Comment by xolod79** [comment]
This is the Core - UNEON. https://www.atari-forum.com/viewtopic.php?t=43391

**Comment by harbaum** [comment]
The IDE interface is rather simple and there already is a SD card implementation for the Tang Nano used by my MiSTeryNano core as well as various other cores. It shouldn't be very complex to wire these two together to get a working setup. 

Did you manage to get video working via HDMI? Compared to that IDE is probably rather easy.
