### ISSUE TITLE
feature idea BL616 Firmware: Analog Paddle Emulation via USB Gamepad Stick(s)

### ISSUE THREAD

**Issue by vossstef** [harbaum/MiSTeryNano#49]
feature idea:

So far digital USB Joystick is supported. 

Replacement of existing DualShock 2 **analog Stick mode** used presently for VIC20 C64 paddle emulation with 
e.g. [USB Logitech Gamepad](https://www.logitechg.com/en-us/products/gamepads/f310-gamepad.940-000110.html) or of course other cheaper brand.

Also **analog Joystick** mode might be useful for other cores that would be addressed as well.

https://www.kernel.org/doc/html/latest/input/gamepad.html

https://github.com/hathach/tinyusb/blob/master/src/class/hid/hid.h

Not sure is such mode supported from gamepads at all...

**Comment by harbaum** [comment]
This should easily be possible. The hid code already reads analogue values if present and currently maps them into digital ones.

I'd suggest to add a status info in the FPGAs hid side which states which joystick data is preferred. Also future cores may want more axes and buttons.

**Comment by vossstef** [comment]
implemented in FPGA Companion firmware
