### ISSUE TITLE
SD Card

### ISSUE THREAD

**Issue by MATRIX7878** [harbaum/MiSTeryNano#53]
Hello,

     I wanted to confirm a few things.

1. This project uses the SD card in SD 4-bit mode
2. I cannot immediately find the SD card calls.  I see the three files in the misc folder, but I cannot find the sd_reader file.  Where do you call the functions to write and read to the SD card?

Thank you

**Comment by harbaum** [comment]
See https://github.com/harbaum/MiSTeryNano/blob/main/src/misc/sd_rw.v

**Comment by MATRIX7878** [comment]
Ah, so it is in 4-bit SD mode.  I see that that file is for reading/writing.  I was asking for an example where data was being transferred.  I guess I was foolishly thinking of seeing a block/multiblock read and write example in the code somewhere.  Thank you though.
