### ISSUE TITLE
Cant find file for µC

### ISSUE THREAD

**Issue by mega-hz** [harbaum/MiSTeryNano#59]
Hi,

i am trying to programm the µC for use as USB-HID but get this error:

[21:19:16.468] - Error: FW:Z:\MiSTeryNano-main\firmware\misterynano_fw\./misterynano_fw_bl616.bin image file is not existed

How to create this file or wher can i find it?

**Comment by harbaum** [comment]
From the same place where you got the ini file:

https://github.com/harbaum/MiSTeryNano/releases

**Comment by mega-hz** [comment]
ok, thank you.
But it was not in the whole zip...

So now it should work wit mouse, keyboard and usb-hub?

And another question: is LPT and SER already on Tang Nano 20K Pins available?

**Comment by mega-hz** [comment]
So i reprogrammed the Onboard BL616 with that file, connected the TangNano to the Input of an USB-C Hub but neither Mouse nor Keyboard are working.
And when i connect Pin73 to GND it doesn't switch to Monochrom.

**Comment by mega-hz** [comment]
Any Idea how to get this run with keyboard on builtin BL616?

**Comment by harbaum** [comment]
I have dropped support for the built-in bl616. On some versions of the tang nano 20k it's connection is broken (a unnecessary capacitor limits the frequency too much), the firmware is now encrypted etc etc ...
