### ISSUE TITLE
Gerber files are corrupted

### ISSUE THREAD

**Issue by grzybsonssg** [harbaum/MiSTeryNano#69]
Hi

Gerber files for MisteryNano shield are corrupted. I can't open any of then with 7zip or Altium Online Viewer, JLPCB gets stuck at 96% when uploading.

**Comment by harbaum** [comment]
These have actually been used for production. Are you sure you downloaded them correctly? If not even 7zip can open them, then it's not even a valid zip file you have there.

**Comment by grzybsonssg** [comment]
You are right, somehow I have downloaded files incorrectly. My apologies.
