### ISSUE TITLE
No mouse/kb on current release

### ISSUE THREAD

**Issue by TzOk83** [harbaum/MiSTeryNano#8]
I've just uploaded the MiSTeryNano filestream and TOS images (1.04UK and 2.06UK) to Tang Nano 20k via OpenFPGALoader. I've also programmed M0S dock with supplied firmware using Bouffalo Flash Cube. Atari boots to the desktop, but there is no keyboard or mouse response.

P.S.
To be able to use OpenFPGALoader under Windows 10, I had to use Zadig to replace the FTDIBUS driver with WinUSB.
These instructions were very helpful:
https://fpga.mit.edu/6205/F22/documentation/openFPGA

**Comment by weav2k4** [comment]
Just updated to the new release and mouse and kb working fine for me.  I know it can be picky on the mouse and kb but my Rii X8 mini keyboard/trackpad works perfectly with it.  Maybe try different ones?

**Comment by TzOk83** [comment]
Yes, today I tried different mice, and one was half-working; it was making only horizontal cursor movements (Logitech M195), but another one (noname mouse) works fine.

The initial problem was, that I built it in the middle of the night after a whole day of work... and the pinout of the Dock is not very intuitive (angled connectors are evil ;) ), so I've managed to put it backward. The good news is, it survived putting 5V to 3V3 line.

I'm leaving this issue, as it may help someone with the OpenFPGALoader issue with the FDTIBUS driver under Windows 10. Apparently, instead of MSYS2/MINGW64, you can also use Windows Subsystem for Linux (Ubuntu on Windows), but you have to update the kernel manually (at least v5.10.60.1): https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
